Traceback (most recent call last):
  File "/p/project1/hai_kg-rag-thesis/scripts/KG_Agent_MK2/./util/extract_entity_list.py", line 165, in <module>
    main()
  File "/p/project1/hai_kg-rag-thesis/scripts/KG_Agent_MK2/./util/extract_entity_list.py", line 162, in main
    transform_json(args.input_file, args.output_file, args.api_key, args.num_questions, args.model, args.llm_switch)
  File "/p/project1/hai_kg-rag-thesis/scripts/KG_Agent_MK2/./util/extract_entity_list.py", line 114, in transform_json
    llm_extracted_entities = extract_entities_with_llm(question_text, api_key, model, llm_switch)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/hai_kg-rag-thesis/scripts/KG_Agent_MK2/./util/extract_entity_list.py", line 37, in extract_entities_with_llm
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/hai_kg-rag-thesis/env/KG_Agent_MK2_venv/lib/python3.11/site-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/hai_kg-rag-thesis/env/KG_Agent_MK2_venv/lib/python3.11/site-packages/openai/resources/chat/completions/completions.py", line 879, in create
    return self._post(
           ^^^^^^^^^^^
  File "/p/project1/hai_kg-rag-thesis/env/KG_Agent_MK2_venv/lib/python3.11/site-packages/openai/_base_client.py", line 1290, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/hai_kg-rag-thesis/env/KG_Agent_MK2_venv/lib/python3.11/site-packages/openai/_base_client.py", line 967, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/p/project1/hai_kg-rag-thesis/env/KG_Agent_MK2_venv/lib/python3.11/site-packages/openai/_base_client.py", line 1071, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.APIStatusError: Error code: 402 - {'error': {'message': 'Insufficient Balance', 'type': 'unknown_error', 'param': None, 'code': 'invalid_request_error'}}
